
MAX_MONSTERS = 8
MIN_MONSTERS = 1

MAX_PODS = 90


function move()
	return {
		{map = "26,-34", fight = true, changeMap = "bottom|right"},
		{map = "27,-34", fight = true, changeMap = "bottom|left"},
		{map = "25,-32", fight = true, changeMap = "bottom|right"},
		{map = "22,-32", fight = true, changeMap = "bottom|left"},
		{map = "22,-31", fight = true, changeMap = "top|bottom|left|right"},
		{map = "25,-31", fight = true, changeMap = "top|bottom|left|right"},
		{map = "24,-31", fight = true, changeMap = "bottom|left|right"},
		{map = "23,-31", fight = true, changeMap = "bottom|left|right"},
		{map = "26,-33", fight = true, changeMap = "top|bottom|right"},
		{map = "26,-32", fight = true, changeMap = "top|bottom|left|right"},
		{map = "28,-31", fight = true, changeMap = "bottom|left"},
		{map = "28,-30", fight = true, changeMap = "top|left"},
		{map = "27,-25", fight = true, changeMap = "top"},
		{map = "27,-26", fight = true, changeMap = "top"},
		{map = "27,-27", fight = true, changeMap = "top|bottom|left"},
		{map = "25,-27", fight = true, changeMap = "top|right"},
		{map = "26,-27", fight = true, changeMap = "top|left|right"},
		{map = "24,-30", fight = true, changeMap = "top|left|right"},
		{map = "25,-30", fight = true, changeMap = "top|bottom|left|right"},
		{map = "25,-29", fight = true, changeMap = "top|bottom|right"},
		{map = "25,-28", fight = true, changeMap = "top|bottom|right"},
		{map = "27,-28", fight = true, changeMap = "top|bottom|left"},
		{map = "27,-29", fight = true, changeMap = "top|bottom|left"},
		{map = "27,-30", fight = true, changeMap = "top|bottom|left|right"},
		{map = "23,-28", fight = true, changeMap = "top|left"},
		{map = "20,-28", fight = true, changeMap = "top|right"},
		{map = "20,-29", fight = true, changeMap = "bottom|right"},
		{map = "21,-32", fight = true, changeMap = "bottom|right"},
		{map = "21,-31", fight = true, changeMap = "top|bottom|right"},
		{map = "21,-30", fight = true, changeMap = "top|bottom|right"},
		{map = "21,-29", fight = true, changeMap = "top|bottom|left|right"},
		{map = "22,-30", fight = true, changeMap = "top|bottom|left|right"},
		{map = "23,-30", fight = true, changeMap = "top|bottom|left|right"},
		{map = "22,-29", fight = true, changeMap = "top|bottom|left|right"},
		{map = "23,-29", fight = true, changeMap = "top|bottom|left"},
		{map = "22,-28", fight = true, changeMap = "top|left|right"},
		{map = "21,-28", fight = true, changeMap = "top|left|right"},
		{map = "26,-28", fight = true, changeMap = "top|bottom|left|right"},
		{map = "26,-29", fight = true, changeMap = "top|bottom|left|right"},
		{map = "26,-30", fight = true, changeMap = "top|bottom|left|right"},
		{map = "26,-31", fight = true, changeMap = "top|bottom|left|right"},
		{map = "27,-31", fight = true, changeMap = "top|bottom|left|right"},
		{map = "27,-32", fight = true, changeMap = "top|bottom|left"},
		{map = "27,-33", fight = true, changeMap = "top|bottom|left"},
		{map = "26,-37", changeMap = "bottom"},
		{map = "26,-36", changeMap = "bottom"},
		{map = "26,-35", changeMap = "bottom"},
		{map = "24,-36", changeMap = "right"},
		{map = "25,-36", changeMap = "right"},
	}
end

function bank()
	return {
		{map = "26,-27", changeMap = "top"},
		{map = "26,-28", changeMap = "top"},
		{map = "26,-29", changeMap = "top"},
		{map = "26,-30", changeMap = "top"},
		{map = "26,-31", changeMap = "top"},
		{map = "26,-32", changeMap = "top"},
		{map = "26,-33", changeMap = "top"},
		{map = "26,-34", changeMap = "top"},
		{map = "26,-35", changeMap = "top"},
		{map = "26,-36", changeMap = "left"},
		{map = "25,-36", changeMap = "left"},
		{map = "25,-30", changeMap = "right"},
		{map = "24,-30", changeMap = "right"},
		{map = "23,-30", changeMap = "right"},
		{map = "22,-30", changeMap = "right"},
		{map = "21,-30", changeMap = "right"},
		{map = "21,-31", changeMap = "bottom"},
		{map = "21,-32", changeMap = "bottom"},
		{map = "22,-32", changeMap = "bottom"},
		{map = "22,-31", changeMap = "bottom"},
		{map = "23,-31", changeMap = "bottom"},
		{map = "24,-31", changeMap = "bottom"},
		{map = "25,-31", changeMap = "right"},
		{map = "25,-32", changeMap = "right"},
		{map = "20,-29", changeMap = "right"},
		{map = "20,-28", changeMap = "right"},
		{map = "21,-28", changeMap = "top"},
		{map = "21,-29", changeMap = "top"},
		{map = "22,-28", changeMap = "top"},
		{map = "22,-29", changeMap = "top"},
		{map = "23,-28", changeMap = "top"},
		{map = "23,-29", changeMap = "top"},
		{map = "25,-27", changeMap = "top"},
		{map = "25,-28", changeMap = "top"},
		{map = "25,-29", changeMap = "top"},
		{map = "27,-25", changeMap = "top"},
		{map = "27,-26", changeMap = "top"},
		{map = "27,-27", changeMap = "left"},
		{map = "27,-28", changeMap = "left"},
		{map = "27,-29", changeMap = "left"},
		{map = "27,-30", changeMap = "left"},
		{map = "28,-30", changeMap = "left"},
		{map = "28,-31", changeMap = "left"},
		{map = "27,-31", changeMap = "left"},
		{map = "27,-32", changeMap = "left"},
		{map = "27,-33", changeMap = "left"},
		{map = "27,-34", changeMap = "left"},
	}
end
