
MAX_MONSTERS = 8
MIN_MONSTERS = 1

MAX_PODS = 90


function move()
	return {
		{map = "-16,4", changeMap = "top"},
		{map = "-16,3", changeMap = "top"},
		{map = "-16,2", changeMap = "top"},
		{map = "-16,1", changeMap = "right"},
		{map = "-15,1", changeMap = "right"},
		{map = "-14,1", changeMap = "right"},
		{map = "-13,1", changeMap = "right"},
		{map = "-12,1", fight = true, changeMap = "top|bottom"},
		{map = "-12,2", fight = true, changeMap = "bottom"},
		{map = "-12,3", fight = true, changeMap = "bottom"},
		{map = "-12,4", fight = true, changeMap = "bottom"},
		{map = "-12,5", fight = true, changeMap = "bottom"},
		{map = "-12,6", fight = true, changeMap = "left"},
		{map = "-13,6", fight = true, changeMap = "left"},
		{map = "-14,6", fight = true, changeMap = "left"},
		{map = "-15,6", fight = true, changeMap = "left"},
		{map = "-16,6", fight = true, changeMap = "left"},
		{map = "-17,6", fight = true, changeMap = "left"},
		{map = "-18,6", fight = true, changeMap = "left"},
		{map = "-12,0", fight = true, changeMap = "top"},
		{map = "-12,-1", fight = true, changeMap = "top"},
		{map = "-12,-2", fight = true, changeMap = "left"},
		{map = "-13,-2", fight = true, changeMap = "left"},
		{map = "-14,-2", fight = true, changeMap = "left"},
		{map = "-15,-2", fight = true, changeMap = "left"},
		{map = "-16,-2", fight = true, changeMap = "left"},
		{map = "-17,-2", fight = true, changeMap = "left"},
		{map = "-18,-2", fight = true, changeMap = "left"},
		{map = "-19,7", fight = true, changeMap = "top|left"},
		{map = "-20,7", fight = true, changeMap = "top|left|right"},
		{map = "-21,7", fight = true, changeMap = "top|left|right"},
		{map = "-22,7", fight = true, changeMap = "top|right"},
		{map = "-22,6", fight = true, changeMap = "top|bottom|right"},
		{map = "-22,5", fight = true, changeMap = "top|bottom|right"},
		{map = "-22,4", fight = true, changeMap = "top|bottom|right"},
		{map = "-22,3", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-22,2", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-22,1", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-23,3", fight = true, changeMap = "right"},
		{map = "-23,2", fight = true, changeMap = "right"},
		{map = "-23,1", fight = true, changeMap = "right"},
		{map = "-22,-2", fight = true, changeMap = "bottom|right"},
		{map = "-21,-2", fight = true, changeMap = "bottom|left|right"},
		{map = "-20,-2", fight = true, changeMap = "bottom|left|right"},
		{map = "-19,-2", fight = true, changeMap = "bottom|left"},
		{map = "-19,-1", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,0", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,1", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,2", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,3", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,4", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,5", fight = true, changeMap = "top|bottom|left"},
		{map = "-19,6", fight = true, changeMap = "top|bottom|left"},
		{map = "-20,6", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,6", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,5", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,5", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,4", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,4", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,3", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,3", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,2", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,2", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,1", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,1", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,0", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-20,-1", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,-1", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-21,0", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-22,0", fight = true, changeMap = "top|bottom|right"},
		{map = "-22,-1", fight = true, changeMap = "top|bottom|right"},
	}
end

function bank()
	return {
		{map = "-16,6", changeMap = "top"},
		{map = "-16,5", changeMap = "top"},
		{map = "-17,4", changeMap = "right"},
		{map = "-18,4", changeMap = "right"},
		{map = "-19,4", changeMap = "right"},
		{map = "-20,4", changeMap = "right"},
		{map = "-21,4", changeMap = "right"},
		{map = "-22,4", changeMap = "right"},
		{map = "-23,3", changeMap = "right"},
		{map = "-23,2", changeMap = "right"},
		{map = "-23,1", changeMap = "right"},
		{map = "-12,4", changeMap = "left"},
		{map = "-13,4", changeMap = "left"},
		{map = "-14,4", changeMap = "left"},
		{map = "-15,4", changeMap = "left"},
		{map = "-16,-2", changeMap = "bottom"},
		{map = "-16,-1", changeMap = "bottom"},
		{map = "-16,0", changeMap = "bottom"},
		{map = "-16,1", changeMap = "bottom"},
		{map = "-16,2", changeMap = "bottom"},
		{map = "-16,3", changeMap = "bottom"},
		{map = "-22,-2", changeMap = "right"},
		{map = "-21,-2", changeMap = "right"},
		{map = "-20,-2", changeMap = "right"},
		{map = "-19,-2", changeMap = "right"},
		{map = "-18,-2", changeMap = "right"},
		{map = "-17,-2", changeMap = "right"},
		{map = "-12,-2", changeMap = "left"},
		{map = "-13,-2", changeMap = "left"},
		{map = "-14,-2", changeMap = "left"},
		{map = "-15,-2", changeMap = "left"},
		{map = "-12,-1", changeMap = "bottom"},
		{map = "-12,0", changeMap = "bottom"},
		{map = "-12,1", changeMap = "bottom"},
		{map = "-12,2", changeMap = "bottom"},
		{map = "-12,3", changeMap = "bottom"},
		{map = "-12,5", changeMap = "top"},
		{map = "-12,6", changeMap = "left"},
		{map = "-13,6", changeMap = "left"},
		{map = "-14,6", changeMap = "left"},
		{map = "-15,6", changeMap = "left"},
		{map = "-18,6", changeMap = "right"},
		{map = "-17,6", changeMap = "right"},
		{map = "-19,7", changeMap = "top"},
		{map = "-19,6", changeMap = "top"},
		{map = "-19,5", changeMap = "top"},
		{map = "-20,7", changeMap = "top"},
		{map = "-20,6", changeMap = "top"},
		{map = "-20,5", changeMap = "top"},
		{map = "-21,7", changeMap = "top"},
		{map = "-21,6", changeMap = "top"},
		{map = "-21,5", changeMap = "top"},
		{map = "-22,7", changeMap = "top"},
		{map = "-22,6", changeMap = "top"},
		{map = "-22,5", changeMap = "top"},
		{map = "-22,-1", changeMap = "bottom"},
		{map = "-22,0", changeMap = "bottom"},
		{map = "-22,1", changeMap = "bottom"},
		{map = "-22,2", changeMap = "bottom"},
		{map = "-22,3", changeMap = "bottom"},
		{map = "-21,-1", changeMap = "bottom"},
		{map = "-21,0", changeMap = "bottom"},
		{map = "-21,1", changeMap = "bottom"},
		{map = "-21,2", changeMap = "bottom"},
		{map = "-21,3", changeMap = "bottom"},
		{map = "-20,-1", changeMap = "bottom"},
		{map = "-20,0", changeMap = "bottom"},
		{map = "-20,1", changeMap = "bottom"},
		{map = "-20,2", changeMap = "bottom"},
		{map = "-20,3", changeMap = "bottom"},
		{map = "-19,-1", changeMap = "bottom"},
		{map = "-19,1", changeMap = "bottom"},
		{map = "-19,0", changeMap = "bottom"},
		{map = "-19,2", changeMap = "bottom"},
		{map = "-19,3", changeMap = "bottom"},
	}
end
