
MAX_MONSTERS = 8
MIN_MONSTERS = 1

MAX_PODS = 90


function move()
	return {
		{map = "-6,-19", fight = true, changeMap = "top|right"},
		{map = "-4,-19", fight = true, changeMap = "top|left"},
		{map = "-6,-28", fight = true, changeMap = "bottom|right"},
		{map = "-3,-23", fight = true, changeMap = "top|left"},
		{map = "-5,-19", fight = true, changeMap = "top|left|right"},
		{map = "-6,-20", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-21", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-22", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-23", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-24", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-25", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-26", fight = true, changeMap = "top|bottom|right"},
		{map = "-6,-27", fight = true, changeMap = "top|bottom|right"},
		{map = "-4,-20", fight = true, changeMap = "top|bottom|left"},
		{map = "-4,-21", fight = true, changeMap = "top|bottom|left"},
		{map = "-4,-22", fight = true, changeMap = "top|bottom|left"},
		{map = "-4,-23", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-28", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-29", fight = true, changeMap = "top|bottom|right"},
		{map = "-4,-37", fight = true, changeMap = "bottom|right"},
		{map = "-5,-20", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-21", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-22", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-23", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-24", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-4,-24", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-4,-25", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-25", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-26", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-5,-27", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-4,-27", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-4,-26", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-3,-24", fight = true, changeMap = "top|bottom|left"},
		{map = "-3,-25", fight = true, changeMap = "top|bottom|left"},
		{map = "-3,-26", fight = true, changeMap = "top|bottom|left"},
		{map = "-3,-27", fight = true, changeMap = "top|bottom|left"},
		{map = "-3,-28", fight = true, changeMap = "top|bottom|left"},
		{map = "-3,-29", fight = true, changeMap = "top|bottom|left"},
		{map = "-5,-30", fight = true, changeMap = "bottom|right"},
		{map = "-3,-30", fight = true, changeMap = "bottom|left"},
		{map = "-4,-30", fight = true, changeMap = "bottom|left|right"},
		{map = "-4,-29", fight = true, changeMap = "top|bottom|left|right"},
		{map = "-4,-28", fight = true, changeMap = "top|bottom|left|right"},
		{map = "5,-18", changeMap = "left"},
		{map = "4,-18", changeMap = "left"},
		{map = "3,-18", changeMap = "left"},
		{map = "2,-18", changeMap = "left"},
		{map = "1,-18", changeMap = "left"},
		{map = "0,-18", changeMap = "left"},
		{map = "-1,-18", changeMap = "top"},
		{map = "-1,-19", changeMap = "left"},
		{map = "-2,-19", changeMap = "left"},
		{map = "-3,-19", changeMap = "left"},
	}
end

function bank()
	return {
		{map = "-6,-19", changeMap = "right"},
		{map = "-5,-19", changeMap = "right"},
		{map = "-4,-19", changeMap = "right"},
		{map = "-3,-19", changeMap = "right"},
		{map = "-2,-19", changeMap = "right"},
		{map = "-1,-19", changeMap = "bottom"},
		{map = "-1,-18", changeMap = "right"},
		{map = "0,-18", changeMap = "right"},
		{map = "1,-18", changeMap = "right"},
		{map = "2,-18", changeMap = "right"},
		{map = "3,-18", changeMap = "right"},
		{map = "-6,-27", changeMap = "bottom"},
		{map = "-6,-28", changeMap = "bottom"},
		{map = "-6,-26", changeMap = "bottom"},
		{map = "-6,-25", changeMap = "bottom"},
		{map = "-6,-24", changeMap = "bottom"},
		{map = "-6,-23", changeMap = "bottom"},
		{map = "-6,-22", changeMap = "bottom"},
		{map = "-6,-21", changeMap = "bottom"},
		{map = "-6,-20", changeMap = "bottom"},
		{map = "-5,-20", changeMap = "bottom"},
		{map = "-5,-21", changeMap = "bottom"},
		{map = "-5,-22", changeMap = "bottom"},
		{map = "-5,-23", changeMap = "bottom"},
		{map = "-5,-24", changeMap = "bottom"},
		{map = "-5,-25", changeMap = "bottom"},
		{map = "-5,-26", changeMap = "bottom"},
		{map = "-5,-27", changeMap = "bottom"},
		{map = "-5,-28", changeMap = "bottom"},
		{map = "-5,-29", changeMap = "bottom"},
		{map = "-5,-30", changeMap = "bottom"},
		{map = "-4,-30", changeMap = "bottom"},
		{map = "-4,-29", changeMap = "bottom"},
		{map = "-4,-28", changeMap = "bottom"},
		{map = "-4,-27", changeMap = "bottom"},
		{map = "-4,-26", changeMap = "bottom"},
		{map = "-4,-25", changeMap = "bottom"},
		{map = "-4,-24", changeMap = "bottom"},
		{map = "-4,-23", changeMap = "bottom"},
		{map = "-4,-22", changeMap = "bottom"},
		{map = "-4,-21", changeMap = "bottom"},
		{map = "-4,-20", changeMap = "bottom"},
		{map = "-3,-23", changeMap = "left"},
		{map = "-3,-24", changeMap = "left"},
		{map = "-3,-25", changeMap = "left"},
		{map = "-3,-26", changeMap = "left"},
		{map = "-3,-27", changeMap = "left"},
		{map = "-3,-28", changeMap = "left"},
		{map = "-3,-29", changeMap = "left"},
		{map = "-3,-30", changeMap = "left"},
	}
end

