
MAX_MONSTERS = 8
MIN_MONSTERS = 1

MAX_PODS = 90


function move()
	return {
		{map = "20,-30", fight = true, changeMap = "top|left"},
		{map = "20,-33", fight = true, changeMap = "bottom|left"},
		{map = "19,-31", fight = true, changeMap = "bottom|right"},
		{map = "20,-31", fight = true, changeMap = "top|bottom|left"},
		{map = "20,-32", fight = true, changeMap = "top|bottom"},
		{map = "19,-33", fight = true, changeMap = "top|right"},
		{map = "19,-29", fight = true, changeMap = "top|left"},
		{map = "16,-31", fight = true, changeMap = "bottom"},
		{map = "18,-29", fight = true, changeMap = "top|left|right"},
		{map = "17,-29", fight = true, changeMap = "top|right"},
		{map = "16,-30", fight = true, changeMap = "top|right"},
		{map = "17,-30", fight = true, changeMap = "bottom|left|right"},
		{map = "18,-30", fight = true, changeMap = "bottom|left|right"},
		{map = "19,-30", fight = true, changeMap = "top|bottom|left|right"},
		{map = "18,-34", fight = true, changeMap = "top|right"},
		{map = "17,-36", fight = true, changeMap = "top|right"},
		{map = "17,-37", fight = true, changeMap = "bottom|right"},
		{map = "19,-40", fight = true, changeMap = "bottom"},
		{map = "19,-39", fight = true, changeMap = "top|bottom|left"},
		{map = "19,-38", fight = true, changeMap = "top|bottom|left"},
		{map = "19,-37", fight = true, changeMap = "top|bottom|left"},
		{map = "19,-36", fight = true, changeMap = "top|bottom|left"},
		{map = "19,-35", fight = true, changeMap = "top|bottom|left"},
		{map = "19,-34", fight = true, changeMap = "top|bottom|left"},
		{map = "18,-35", fight = true, changeMap = "top|bottom|right"},
		{map = "18,-36", fight = true, changeMap = "top|bottom|left|right"},
		{map = "18,-37", fight = true, changeMap = "top|bottom|left|right"},
		{map = "18,-38", fight = true, changeMap = "top|bottom|right"},
		{map = "18,-39", fight = true, changeMap = "bottom|right"},
		{map = "26,-37", changeMap = "bottom"},
		{map = "26,-36", changeMap = "bottom"},
		{map = "26,-35", changeMap = "bottom"},
		{map = "26,-34", changeMap = "bottom"},
		{map = "26,-33", changeMap = "bottom"},
		{map = "26,-32", changeMap = "bottom"},
		{map = "26,-31", changeMap = "left"},
		{map = "25,-31", changeMap = "left"},
		{map = "24,-31", changeMap = "left"},
		{map = "23,-31", changeMap = "left"},
		{map = "22,-31", changeMap = "left"},
		{map = "21,-31", changeMap = "top"},
		{map = "21,-32", changeMap = "left"},
		{map = "24,-36", changeMap = "right"},
		{map = "25,-36", changeMap = "right"},
	}
end

function bank()
	return {
		{map = "20,-32", changeMap = "right"},
		{map = "21,-32", changeMap = "bottom"},
		{map = "21,-31", changeMap = "right"},
		{map = "22,-31", changeMap = "right"},
		{map = "23,-31", changeMap = "right"},
		{map = "24,-31", changeMap = "right"},
		{map = "25,-31", changeMap = "right"},
		{map = "26,-31", changeMap = "top"},
		{map = "26,-32", changeMap = "top"},
		{map = "26,-33", changeMap = "top"},
		{map = "26,-34", changeMap = "top"},
		{map = "26,-35", changeMap = "top"},
		{map = "26,-36", changeMap = "left"},
		{map = "25,-36", changeMap = "left"},
		{map = "19,-40", changeMap = "bottom"},
		{map = "19,-39", changeMap = "bottom"},
		{map = "19,-38", changeMap = "bottom"},
		{map = "19,-37", changeMap = "bottom"},
		{map = "19,-36", changeMap = "bottom"},
		{map = "19,-35", changeMap = "bottom"},
		{map = "19,-34", changeMap = "bottom"},
		{map = "19,-33", changeMap = "right"},
		{map = "18,-34", changeMap = "right"},
		{map = "18,-35", changeMap = "right"},
		{map = "18,-36", changeMap = "right"},
		{map = "17,-36", changeMap = "right"},
		{map = "17,-37", changeMap = "right"},
		{map = "18,-37", changeMap = "right"},
		{map = "18,-38", changeMap = "right"},
		{map = "18,-39", changeMap = "right"},
		{map = "20,-33", changeMap = "bottom"},
		{map = "16,-31", changeMap = "bottom"},
		{map = "16,-30", changeMap = "right"},
		{map = "17,-30", changeMap = "right"},
		{map = "18,-30", changeMap = "right"},
		{map = "19,-30", changeMap = "right"},
		{map = "20,-30", changeMap = "top"},
		{map = "20,-31", changeMap = "top"},
		{map = "19,-29", changeMap = "top"},
		{map = "18,-29", changeMap = "top"},
		{map = "17,-29", changeMap = "top"},
		{map = "19,-31", changeMap = "right"},
	}
end
